### ISSUE TITLE
keep it up

### ISSUE THREAD

**Issue by europer** [netmonk/esp-ecp#1]
I have no questions just to say it fantasic that  somebody is developing more here in dshot and esp32. Im also in the process of using esp32 (love this small mc) for my first drone so I cannot at given time contribute so much here, since I am a normal hobby programmer what use the esp32 for homeatic IoT, MQTT, Node-red so the speed is not that BIG issue so I am working me in to the multi task, core 0 an1, timer and interrupts.....so was in the past not really a big issue (just the interrups) but this is of course a different liga...that the reason I do it, to bring my self a lever higher, and the fun of doing things what is perhaps not needed...but is a hobby...
again...fantastic that your into this
best regards

**Comment by netmonk** [comment]
Well thank you very much at first for your kind words. 
Yes somehow it is quite difficult when you start to walk through new territories but after some time it feels just like business as usual. 

The biggest point right now, is to move from arduino frame work to esp-idf, i will post some code soon

**Comment by europer** [comment]
Hi, can I ask you why you go from arduino frame work to esp-idf? I use now platformio with arduino frame and freertos or you mean in the coding like as example from the esp-idf :

#if CONFIG_FREERTOS_UNICORE
#define ARDUINO_RUNNING_CORE 0
#else
#define ARDUINO_RUNNING_CORE 1
#endif

TaskHandle_t loop1;

void myTask(void *pvParameters) {
  int taskno = (int)pvParameters;

  while (1) {
  }
}

void setup() {
  Serial.begin(115200);
  //xTaskCreatePinnedToCore(TaskFunktion, Taskname, Stack size of tast, parament of tast, pro of tast, task handle, core (0 or 1);
  xTaskCreatePinnedToCore(myTask, "loop1", 4096, (void *)1, 1, &loop1, ARDUINO_RUNNING_CORE);
}

void loop() {
  // nope, do nothing here
  vTaskDelay(portMAX_DELAY); // wait as much as posible ...
}


br

PS: yes I see your using it...so sorry for my lack of knowlege...what do you mean to go from arduino frame work...some links? I did try to google it but no really good explanaiton to find, but every day learning something new is good :)

**Comment by netmonk** [comment]
well Arduino framework is very good for begining to play with MCU. 
It is very high level programming and most of libraries available are easy to use at the cost of limiting the use of full potential of the hardware plateform. 

So it is very easy to prototype little projects  fastly like getting temperature from sensor and push 
data over internet using wifi. But indeed, the firmware will be quite big embedding all libraries you dont know about, and lotsa cpu cycles will be lost to cross all the hundreds of layer between high abstraction layer and bare metal hardware. 

When you need to go deeper in hardware control, with faster code and smaller firmware footprint, going back to pure C is the rule. 
Espressif, owner of ESP32 are providing very efficient esp-idf developpement framework wich give access to full hardware. 
The cost is that your code is more complex, as far as you need to manage all the thing arduino library is managing to you. 

For exemple, im currently working on i2c https://github.com/netmonk/i2cscanner you can have a look of my i2c scanner written in esp-idf with a basic arduino i2c scanner https://playground.arduino.cc/Main/I2cScanner/
