### ISSUE TITLE
Question about timing

### ISSUE THREAD

**Issue by MichaelVoelkel** [netmonk/esp-ecp#2]
Hi,

great code and thanks for it! I have not tried it (yet) but will do soon.

One question about the code: You seem to call the interrupt timer with 2KHz, so only every 500 µs. When the interrupt is called, you write via rmt once (?) the sequence of 16 bits, where each bit takes up 1,67µS, so 16 * 1,67µS = 26,72µS in total. So, within the other 500 - 26,72 = 473,28 µS, you do nothing. Will the motor in this time not just idle? Probably, I have misunderstood something here, though. I would love an answer, although I understand if there is no time for answering!

**Comment by netmonk** [comment]
thank you for your comment. 
Just dont forget that the esp32 using this piece of code is talking to another mcu running the ESC firmware controlling the motor.
In my case, the firmware running in the ESC is blheli32 (running on a 32bit stm32 mcu). So this esc is linked to the esp to receive orders and to translate it to physical effect (such as allowing current go through mosfet to feed motor wire).  

The code Implement dshot 600 digital protocol which permit to send a value between 0 to 2000 in very short time using a time sequence of high/low (the RMT part of the code). 
The ESC firmware will translate the numerical value received, and will power the motor adequatly. 
the ESC firmware will maintain the command of the engine, until it receives a new command, or the delay of receiving a new command timeouts. 
the delay is quite high, like dozen of milliseconds. before the firmware fallback in timeout status.
so there is no need to send plenty of message or increase message frequency to very high rate to get the engine running.

more over, too high frequency is quite dangerous with the motor, and pose some risk to it.

**Comment by MichaelVoelkel** [comment]
Ahhh, this makes absolute sense. Thank your for clarifying this! I was fearing that I needed to send these 16 bits in a loop non-stop. If the ESC maintains the state, this is way more comfortable, of course. I am currently running my ESP32 with Espressif, so I cannot use the setup/loop code, but I will try with another device soon. Thank you again, it was really hard to find Dshot code working with ESP

**Comment by netmonk** [comment]
well im currently trying to port this arduino code to espressif pure C. 
I need to buy an osciloscope to really see  the output on the pin cause currently it's not working at all. 
(i cannot succeed to arm the esc). 
you should read this https://img.banggood.com/file/products/20171201012630BLHeli_32%20manual%20ARM%20Rev32.x.pdf 
which is the bhleli32 manual explaining how the esc is working
