### ISSUE TITLE
Speed change based on potentiometer

### ISSUE THREAD

**Issue by jimmywuhkust** [netmonk/esp-ecp#3]
Hi, thank you so much for developing how to drive Dshot with ESP32. I have a slight problem with the example code. I am not able to change the speed of the motor based on the Potentiometer attached to Pin 34, which is outputting voltage from 0-3.3V, may I know if there is anything I need to change in the code for it to work? Thanks a lot!

**Comment by netmonk** [comment]
hello, 
The latest version of code isnt working with a potentiometer. it's more like a sin wave (going up and down). 

Better check history commit. Im sorry that i didnt update the readme about this.

**Comment by jimmywuhkust** [comment]
Dear netmonk,

Thank you for your reply! May I know then what I can modify to change the speed of the motor? As the test code is spinning the motor quite slowly. Let me check the history commit to see if I can find one that works with the potentiometer.

**Comment by netmonk** [comment]
you need to plug a potentiometer and read the voltage value. if you knoz the max voltage value you can map from zero to this max value for 0 to 2000 value which is the value you send to the esc via dshot

**Comment by jimmywuhkust** [comment]
I just got it to work! Thank you so much. It turns out your code is working, but as my motor has too low of a KV, I didn't see any difference. Thank you again for your help.
